# Generated by Django 3.0.6 on 2020-08-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20200818_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='blogapp.Categorie'),
        ),
    ]
